version: "3"

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    restart: always
    volumes:
      - /your_uploads_dir/uploads:/app/uploads
    ports:
      - 3001:3001
    networks:
      - app_network
    env_file:
      - .env
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        - WEB_PORT=3000
        - SERVER_PORT=3001
        - API_URL=http://localhost:3001
        - STATIC_PATH=/static
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
    env_file:
      - .env
    depends_on:
      - api

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
