version: '3'
services:
  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1241
    ports:
      - "3306:3306"

  redis:
    image: redis
    ports:
      - "6379:6379"
