name: Build & Test

on:
  push:
    branches:
      - master
      - v[0-9]+.[0-9]+.x-staging
      - v[0-9]+.[0-9]+.x
    paths-ignore:
      - README.md
      - .github/**
      - "!.github/workflows/build.yml"
      - "!.github/actions/build-rust/action.yml"
      - "!.github/actions/setup-node/action.yml"
  pull_request:
  merge_group:
    branches:
      - master
      - v[0-9]+.[0-9]+.x-staging
      - v[0-9]+.[0-9]+.x

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup caching
        uses: actions/cache@v2
        with:
          path: ${{ env.PNPM_CACHE_FOLDER }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.x

      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "pnpm"

      - name: setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile && ls -a && git status

      - name: Run Tests
        run: pnpm ci:test
